GET http://localhost:3001/api/v1/clients
# Content-Type: application/json

# {
#   "name": "Juan Carlos",
#   "lastname": "Rivera",
#   "phone": "+505 2222 2222",
#   "municipio": "",
#   "city": "",
#   "country": "",
#   "address": ""
# }