services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=jahaira_store
      - POSTGRES_USER=rey
      - POSTGRES_PASSWORD=0000
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
